# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/jammy64"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "182.0.0.10"

    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end

    jenkins.vm.provision "shell", path: "scripts/setup-node.sh"
    jenkins.vm.provision "shell", path: "scripts/setup-jenkins.sh"

    jenkins.vm.provision "file", source: "keys/jenkins_prod_key", destination: "/home/vagrant/.ssh/id_rsa"
    jenkins.vm.provision "shell", inline: <<-SHELL
      chmod 600 /home/vagrant/.ssh/id_rsa
      chown vagrant:vagrant /home/vagrant/.ssh/id_rsa
      cat <<-CONFIG > /home/vagrant/.ssh/config
Host prod
  HostName 182.0.0.20
  User vagrant
  StrictHostKeyChecking no
  UserKnownHostsFile=/dev/null
CONFIG
      chmod 600 /home/vagrant/.ssh/config
      chown vagrant:vagrant /home/vagrant/.ssh/config
    SHELL
  end

  config.vm.define "prod" do |prod|
    prod.vm.box = "ubuntu/jammy64"
    prod.vm.hostname = "prod"
    prod.vm.network "private_network", ip: "182.0.0.20"

    prod.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    prod.vm.provision "shell", path: "scripts/setup-node.sh"

    prod.vm.provision "file", source: "keys/jenkins_prod_key.pub", destination: "/tmp/jenkins_prod_key.pub"
    prod.vm.provision "shell", inline: <<-SHELL
      mkdir -p /home/vagrant/.ssh
      chmod 700 /home/vagrant/.ssh
      cat /tmp/jenkins_prod_key.pub >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant /home/vagrant/.ssh
    SHELL
  end

end
